name: Update apt repository

# Run this workflow manually after a PackSquash release is made
on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    env:
      REPO_ARCHITECTURES: |
        amd64
        arm64
      # Change these two for each release
      PARTIAL_PACKAGE_FILE_NAME: packsquash_0.3.0
      PACKAGE_REVISION: '-3'

      # Make git commit author and committer look fancy
      GIT_AUTHOR_NAME: github-actions[bot]
      GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
      GIT_COMMITTER_NAME: github-actions[bot]
      GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com

    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        arch: ['amd64', 'arm64']

    steps:
      - name: 'Download ${{ matrix.arch }} Debian package'
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: 5482008
          workflow_conclusion: success
          event: release
          name: 'Debian package (${{ matrix.arch }})'
          path: '.${{ matrix.arch }}'
          repo: ComunidadAylas/PackSquash

      - name: 'Add ${{ matrix.arch }} Debian package'
        uses: jrandiny/apt-repo-action@v2.0.1
        with:
          repo_supported_version: stable
          file_target_version: stable
          page_branch: apt-repo
          repo_folder: debian
          github_token: ${{ secrets.GH_API_TOKEN }}
          repo_supported_arch: ${{ env.REPO_ARCHITECTURES }}
          file: '.${{ matrix.arch }}/${{ env.PARTIAL_PACKAGE_FILE_NAME }}${{ env.PACKAGE_REVISION }}_${{ matrix.arch }}.deb'
          public_key: ${{ secrets.APT_PUBLIC_KEY }}
          private_key: ${{ secrets.APT_PRIVATE_KEY }}
          key_passphrase: ${{ secrets.APT_PRIVATE_KEY_PASSPHRASE }}
