name: Update apt repository

# Run this workflow manually after a PackSquash release is made
on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download amd64 Debian package
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GH_API_TOKEN }}
          workflow: Build
          workflow_conclusion: success
          branch: master
          # TODO: change to release
          event: push
          name: Debian package (amd64)
          path: .amd64
          repo: ComunidadAylas/PackSquash

      - name: Add amd64 Debian package
        uses: jrandiny/apt-repo-action@v2.0.1
        with:
          github_token: ${{ secrets.GH_API_TOKEN }}
          arch: |
            amd64
            arm64
          version: all
          # Change this file name accordingly
          file: .amd64/packsquash_0.3.0~rc.1_amd64.deb
          file_target_version: all
          public_key: ${{ secrets.APT_PUBLIC_KEY }}
          private_key: ${{ secrets.APT_PRIVATE_KEY }}
          key_passphrase: ${{ secrets.APT_PRIVATE_KEY_PASSPHRASE }}
          page_branch: apt-repo
          repo_folder: debian
          debug: true

      - name: Download arm64 Debian package
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GH_API_TOKEN }}
          workflow: Build
          workflow_conclusion: success
          branch: master
          # TODO: change to release
          event: push
          name: Debian package (arm64)
          path: .arm64
          repo: ComunidadAylas/PackSquash

      - name: Add arm64 Debian package
        uses: jrandiny/apt-repo-action@v2.0.1
        with:
          github_token: ${{ secrets.GH_API_TOKEN }}
          arch: |
            amd64
            arm64
          version: all
          # Change this file name accordingly
          file: .arm64/packsquash_0.3.0~rc.1_arm64.deb
          file_target_version: all
          public_key: ${{ secrets.APT_PUBLIC_KEY }}
          private_key: ${{ secrets.APT_PRIVATE_KEY }}
          key_passphrase: ${{ secrets.APT_PRIVATE_KEY_PASSPHRASE }}
          page_branch: apt-repo
          repo_folder: debian
          debug: true
